export {default as A } from './a.jpg'
export {default as B } from './b.jpg'
export {default as C } from './a.jpg'
export {default as D} from './c.jpg'
export {default as E } from './d.jpg'
export {default as F } from './e.jpg'
export {default as G } from './f.jpg'
export {default as H } from './h.jpg'
export {default as I } from './i.jpg'
export {default as J } from './j.jpg'
export {default as K } from './k.jpg'
export {default as L } from './l.jpg'
export {default as M } from './m.jpg'
export {default as N } from './n.jpg'
export {default as O } from './o.jpg'
export {default as P } from './p.jpg'
export {default as Q } from './q.jpg'
export {default as R } from './r.jpg'
export {default as S } from './s.jpg'
export {default as T } from './t.jpg'

export {default as weare} from './weare.jpg'
